import UIKit
import MetalKit

final class GameViewController: UIViewController {
    private var engine: METSEEngineBridge?
    private let statusLabel=UILabel(); private let leftPad=UIView(); private let rightPad=UIView()
    private var leftStart=CGPoint.zero; private var rightLast=CGPoint.zero
    override func viewDidLoad(){ super.viewDidLoad(); view.backgroundColor=.black; guard let device=MTLCreateSystemDefaultDevice() else{return}; let metal=MTKView(frame:.zero,device:device); view.addSubview(metal); metal.translatesAutoresizingMaskIntoConstraints=false; NSLayoutConstraint.activate([metal.leadingAnchor.constraint(equalTo:view.leadingAnchor),metal.trailingAnchor.constraint(equalTo:view.trailingAnchor),metal.topAnchor.constraint(equalTo:view.topAnchor),metal.bottomAnchor.constraint(equalTo:view.bottomAnchor)]); engine=METSEEngineBridge(view:metal); engine?.start(); configureHUD(); configureInput() }
    override func viewWillAppear(_ animated:Bool){super.viewWillAppear(animated);navigationController?.setNavigationBarHidden(true,animated:animated)}
    override func viewWillDisappear(_ animated:Bool){super.viewWillDisappear(animated);engine?.setMoveForward(0,strafe:0);if isMovingFromParent{engine?.stop()}}
    private func configureHUD(){
        let back=UIButton(type:.system); back.setImage(UIImage(systemName:"chevron.backward"),for:.normal); back.tintColor=.white; back.backgroundColor=UIColor.black.withAlphaComponent(0.32); back.layer.cornerRadius=22; back.addAction(UIAction{[weak self]_ in self?.navigationController?.popViewController(animated:true)},for:.touchUpInside)
        statusLabel.text="ENGINE ONLINE • 60HZ"; statusLabel.font=.monospacedSystemFont(ofSize:10,weight:.semibold); statusLabel.textColor=UIColor(red:0.55,green:0.92,blue:0.75,alpha:1); statusLabel.backgroundColor=UIColor.black.withAlphaComponent(0.30); statusLabel.textAlignment=.center; statusLabel.layer.cornerRadius=10;statusLabel.layer.masksToBounds=true
        [back,statusLabel].forEach{view.addSubview($0);$0.translatesAutoresizingMaskIntoConstraints=false}; NSLayoutConstraint.activate([back.leadingAnchor.constraint(equalTo:view.safeAreaLayoutGuide.leadingAnchor,constant:12),back.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor,constant:10),back.widthAnchor.constraint(equalToConstant:44),back.heightAnchor.constraint(equalToConstant:44),statusLabel.leadingAnchor.constraint(equalTo:back.trailingAnchor,constant:10),statusLabel.centerYAnchor.constraint(equalTo:back.centerYAnchor),statusLabel.widthAnchor.constraint(greaterThanOrEqualToConstant:150),statusLabel.heightAnchor.constraint(equalToConstant:30)])
        let fire=UIButton(type:.system); fire.setImage(UIImage(systemName:"scope"),for:.normal); fire.tintColor=.white; fire.backgroundColor=UIColor(red:0.72,green:0.18,blue:0.10,alpha:0.72); fire.layer.cornerRadius=34; fire.addAction(UIAction{[weak self]_ in self?.engine?.triggerFire()},for:.touchUpInside); view.addSubview(fire); fire.translatesAutoresizingMaskIntoConstraints=false; NSLayoutConstraint.activate([fire.trailingAnchor.constraint(equalTo:view.safeAreaLayoutGuide.trailingAnchor,constant:-20),fire.bottomAnchor.constraint(equalTo:view.safeAreaLayoutGuide.bottomAnchor,constant:-20),fire.widthAnchor.constraint(equalToConstant:68),fire.heightAnchor.constraint(equalToConstant:68)])
    }
    private func configureInput(){
        leftPad.backgroundColor=.clear;rightPad.backgroundColor=.clear;view.insertSubview(leftPad,belowSubview:statusLabel);view.insertSubview(rightPad,belowSubview:statusLabel);leftPad.translatesAutoresizingMaskIntoConstraints=false;rightPad.translatesAutoresizingMaskIntoConstraints=false
        NSLayoutConstraint.activate([leftPad.leadingAnchor.constraint(equalTo:view.leadingAnchor),leftPad.bottomAnchor.constraint(equalTo:view.bottomAnchor),leftPad.topAnchor.constraint(equalTo:view.centerYAnchor),leftPad.widthAnchor.constraint(equalTo:view.widthAnchor,multiplier:0.44),rightPad.trailingAnchor.constraint(equalTo:view.trailingAnchor),rightPad.topAnchor.constraint(equalTo:view.topAnchor),rightPad.bottomAnchor.constraint(equalTo:view.bottomAnchor),rightPad.widthAnchor.constraint(equalTo:view.widthAnchor,multiplier:0.50)])
        let lp=UIPanGestureRecognizer(target:self,action:#selector(movePan(_:)));leftPad.addGestureRecognizer(lp);let rp=UIPanGestureRecognizer(target:self,action:#selector(lookPan(_:)));rightPad.addGestureRecognizer(rp)
    }
    @objc private func movePan(_ g:UIPanGestureRecognizer){ let p=g.location(in:leftPad); if g.state == .began{leftStart=p}; let dx=Float((p.x-leftStart.x)/70.0); let dy=Float((p.y-leftStart.y)/70.0); if g.state == .ended || g.state == .cancelled{engine?.setMoveForward(0,strafe:0)}else{engine?.setMoveForward(max(-1,min(1,-dy)),strafe:max(-1,min(1,dx)))} }
    @objc private func lookPan(_ g:UIPanGestureRecognizer){ let p=g.location(in:rightPad); if g.state == .began{rightLast=p;return}; let dx=Float(p.x-rightLast.x)*0.0042; let dy=Float(p.y-rightLast.y)*0.0035; rightLast=p; engine?.addLookYaw(dx,pitch:-dy) }
}
