import UIKit

final class GatewayViewController: UIViewController {
    private let gradient = CAGradientLayer()
    override var prefersStatusBarHidden: Bool { true }
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask { .landscape }
    override var preferredInterfaceOrientationForPresentation: UIInterfaceOrientation { .landscapeRight }
    override func viewDidLoad(){super.viewDidLoad();configureBackground();configureLayout()}
    override func viewWillAppear(_ animated:Bool){super.viewWillAppear(animated);navigationController?.setNavigationBarHidden(true,animated:animated)}
    override func viewDidLayoutSubviews(){super.viewDidLayoutSubviews();gradient.frame=view.bounds}
    private func configureBackground(){view.backgroundColor=UIColor(red:0.006,green:0.012,blue:0.014,alpha:1);gradient.colors=[UIColor(red:0.018,green:0.065,blue:0.055,alpha:1).cgColor,UIColor(red:0.006,green:0.012,blue:0.014,alpha:1).cgColor];gradient.startPoint=CGPoint(x:0,y:0);gradient.endPoint=CGPoint(x:1,y:1);view.layer.insertSublayer(gradient,at:0)}
    private func configureLayout(){let root=UIStackView();root.axis=.horizontal;root.spacing=24;root.distribution=.fillEqually;root.translatesAutoresizingMaskIntoConstraints=false;view.addSubview(root);NSLayoutConstraint.activate([root.leadingAnchor.constraint(equalTo:view.safeAreaLayoutGuide.leadingAnchor,constant:28),root.trailingAnchor.constraint(equalTo:view.safeAreaLayoutGuide.trailingAnchor,constant:-28),root.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor,constant:22),root.bottomAnchor.constraint(equalTo:view.safeAreaLayoutGuide.bottomAnchor,constant:-22)]);root.addArrangedSubview(makeHero());root.addArrangedSubview(makeModules())}
    private func makeHero()->UIView{let eyebrow=UILabel();eyebrow.text="MIDDLE EAST TACTICAL SIMULATION ENGINE";eyebrow.font=.monospacedSystemFont(ofSize:11,weight:.semibold);eyebrow.textColor=UIColor(red:0.46,green:0.82,blue:0.67,alpha:1);eyebrow.adjustsFontSizeToFitWidth=true;eyebrow.minimumScaleFactor=0.72;let title=UILabel();title.text="METSE";title.font=.systemFont(ofSize:54,weight:.black);title.textColor=.white;let subtitle=UILabel();subtitle.text="مركز القيادة";subtitle.font=.systemFont(ofSize:25,weight:.semibold);subtitle.textColor=UIColor.white.withAlphaComponent(0.70);var config=UIButton.Configuration.filled();config.title="ابدأ جلسة تكتيكية";config.subtitle="دخول مباشر إلى المحرك";config.image=UIImage(systemName:"play.fill");config.imagePadding=14;config.cornerStyle=.large;config.baseBackgroundColor=UIColor(red:0.18,green:0.56,blue:0.42,alpha:1);config.baseForegroundColor=.white;config.contentInsets=NSDirectionalEdgeInsets(top:18,leading:22,bottom:18,trailing:22);let playButton=UIButton(configuration:config);playButton.contentHorizontalAlignment=.leading;playButton.heightAnchor.constraint(greaterThanOrEqualToConstant:82).isActive=true;playButton.addAction(UIAction{[weak self]_ in self?.openGame()},for:.touchUpInside);let metadata=UILabel();metadata.text="BUILD 006  •  CHARACTER MOTOR  •  NATIVE METAL  •  32 MAX";metadata.font=.monospacedSystemFont(ofSize:10,weight:.medium);metadata.textColor=UIColor.white.withAlphaComponent(0.42);metadata.numberOfLines=2;let spacer=UIView();spacer.setContentHuggingPriority(.defaultLow,for:.vertical);let stack=UIStackView(arrangedSubviews:[eyebrow,title,subtitle,spacer,playButton,metadata]);stack.axis=.vertical;stack.spacing=8;return stack}
    private func makeModules()->UIView{let heading=UILabel();heading.text="الأنظمة";heading.font=.systemFont(ofSize:20,weight:.bold);heading.textColor=.white;let grid=UIStackView();grid.axis=.vertical;grid.spacing=10;grid.distribution=.fillEqually;let modules=GatewayModule.secondary;for rowStart in stride(from:0,to:modules.count,by:2){let row=UIStackView();row.axis=.horizontal;row.spacing=10;row.distribution=.fillEqually;for index in rowStart..<min(rowStart+2,modules.count){let module=modules[index];let card=GatewayCardButton(module:module);card.addAction(UIAction{[weak self]_ in self?.open(module.destination)},for:.touchUpInside);row.addArrangedSubview(card)};if row.arrangedSubviews.count==1{row.addArrangedSubview(UIView())};grid.addArrangedSubview(row)};let stack=UIStackView(arrangedSubviews:[heading,grid]);stack.axis=.vertical;stack.spacing=12;return stack}
    private func openGame(){navigationController?.pushViewController(GameViewController(),animated:true)}
    private func open(_ destination:GatewayModule.Destination){navigationController?.setNavigationBarHidden(false,animated:true);switch destination{case .game:openGame();case .updates:navigationController?.pushViewController(UpdateCenterViewController(),animated:true);default:navigationController?.pushViewController(ModulePlaceholderViewController(destination:destination),animated:true)}}
}
