#include "METSECharacterMotor.hpp"
#include <algorithm>
#include <cmath>
namespace metse { namespace {bool pf(double v){return std::isfinite(v)&&v>0;} double sign(double v){return v<0?-1.0:1.0;}}
CharacterMotor::CharacterMotor(CharacterConfig c)noexcept:config_(c){if(!pf(config_.walkSpeed))config_.walkSpeed=1.55;if(!pf(config_.tacticalSpeed))config_.tacticalSpeed=2.65;if(!pf(config_.jogSpeed))config_.jogSpeed=4.15;if(!pf(config_.sprintSpeed))config_.sprintSpeed=6.0;config_.tacticalSpeed=std::max(config_.tacticalSpeed,config_.walkSpeed);config_.jogSpeed=std::max(config_.jogSpeed,config_.tacticalSpeed);config_.sprintSpeed=std::max(config_.sprintSpeed,config_.jogSpeed);if(!pf(config_.crouchSpeed))config_.crouchSpeed=2;if(!pf(config_.proneSpeed))config_.proneSpeed=.82;if(!pf(config_.backwardMultiplier)||config_.backwardMultiplier>1)config_.backwardMultiplier=.76;if(!pf(config_.groundAcceleration))config_.groundAcceleration=15;if(!pf(config_.groundDeceleration))config_.groundDeceleration=19;if(!pf(config_.airAcceleration))config_.airAcceleration=3;if(!pf(config_.gravity))config_.gravity=18;if(!pf(config_.bodyTurnRate))config_.bodyTurnRate=3.6;if(!pf(config_.viewYawSoftLimit))config_.viewYawSoftLimit=.60;if(!pf(config_.viewYawHardLimit)||config_.viewYawHardLimit<=config_.viewYawSoftLimit)config_.viewYawHardLimit=1.22;if(!pf(config_.maxPitch)||config_.maxPitch>1.45)config_.maxPitch=1.10;if(!pf(config_.standingEyeHeight))config_.standingEyeHeight=1.64;if(!pf(config_.crouchedEyeHeight)||config_.crouchedEyeHeight>=config_.standingEyeHeight)config_.crouchedEyeHeight=1.08;if(!pf(config_.proneEyeHeight)||config_.proneEyeHeight>=config_.crouchedEyeHeight)config_.proneEyeHeight=.42;if(!pf(config_.eyeHeightTransitionSpeed))config_.eyeHeightTransitionSpeed=3;if(!pf(config_.capsuleRadius))config_.capsuleRadius=.34;if(!pf(config_.standingCapsuleHeight))config_.standingCapsuleHeight=1.78;if(!pf(config_.crouchedCapsuleHeight)||config_.crouchedCapsuleHeight>=config_.standingCapsuleHeight)config_.crouchedCapsuleHeight=1.18;if(!pf(config_.proneCapsuleHeight)||config_.proneCapsuleHeight>=config_.crouchedCapsuleHeight)config_.proneCapsuleHeight=.52;reset();}
void CharacterMotor::reset()noexcept{state_={};state_.eyeHeight=config_.standingEyeHeight;state_.grounded=true;state_.stance=CharacterStance::Standing;state_.gait=CharacterGait::Idle;}
void CharacterMotor::addLookInput(double y,double p)noexcept{if(!std::isfinite(y)||!std::isfinite(p))return;y=std::clamp(y,-.35,.35);p=std::clamp(p,-.25,.25);state_.viewYawOffset=std::clamp(state_.viewYawOffset+y,-config_.viewYawHardLimit,config_.viewYawHardLimit);state_.pitch=std::clamp(state_.pitch+p,-config_.maxPitch,config_.maxPitch);}
void CharacterMotor::cycleStance()noexcept{switch(state_.stance){case CharacterStance::Standing:state_.stance=CharacterStance::Crouched;break;case CharacterStance::Crouched:state_.stance=CharacterStance::Prone;break;case CharacterStance::Prone:state_.stance=CharacterStance::Standing;break;}state_.sprinting=false;state_.gait=CharacterGait::Idle;}
void CharacterMotor::updateGait(double m,double f,bool sprint)noexcept{state_.sprinting=false;if(m<=.02){state_.gait=CharacterGait::Idle;return;}if(state_.stance==CharacterStance::Crouched){state_.gait=CharacterGait::Crouch;return;}if(state_.stance==CharacterStance::Prone){state_.gait=CharacterGait::Crawl;return;}if(sprint&&f>.35&&m>.78){state_.sprinting=true;state_.gait=CharacterGait::Sprint;}else if(m<.34)state_.gait=CharacterGait::Walk;else if(m<.72)state_.gait=CharacterGait::Tactical;else state_.gait=CharacterGait::Jog;}
void CharacterMotor::fixedStep(double dt,const CharacterInput& raw)noexcept{if(!pf(dt))return;double f=std::clamp(raw.forward,-1.0,1.0),s=std::clamp(raw.strafe,-1.0,1.0),m=std::hypot(f,s);if(m>1){f/=m;s/=m;m=1;}double excess=std::abs(state_.viewYawOffset)-config_.viewYawSoftLimit;if(excess>0){double turn=std::min(excess,config_.bodyTurnRate*dt),st=sign(state_.viewYawOffset)*turn;state_.bodyYaw=wrapAngle(state_.bodyYaw+st);state_.viewYawOffset-=st;}updateGait(m,f,raw.sprintHeld);double limit=0;switch(state_.gait){case CharacterGait::Idle:break;case CharacterGait::Walk:limit=config_.walkSpeed;break;case CharacterGait::Tactical:limit=config_.tacticalSpeed;break;case CharacterGait::Jog:limit=config_.jogSpeed;break;case CharacterGait::Sprint:limit=config_.sprintSpeed;break;case CharacterGait::Crouch:limit=config_.crouchSpeed;break;case CharacterGait::Crawl:limit=config_.proneSpeed;break;}if(f<-.05)limit*=config_.backwardMultiplier;bool moving=m>.02;double nf=moving?f/m:0,ns=moving?s/m:0,sy=std::sin(state_.bodyYaw),cy=std::cos(state_.bodyYaw);double tx=moving?(sy*nf+cy*ns)*limit:0,tz=moving?(cy*nf-sy*ns)*limit:0,response=state_.grounded?(moving?config_.groundAcceleration:config_.groundDeceleration):config_.airAcceleration;double previousSpeed=horizontalSpeed();state_.velocityX=moveToward(state_.velocityX,tx,response*dt);state_.velocityZ=moveToward(state_.velocityZ,tz,response*dt);if(!state_.grounded||state_.y>1e-6||state_.velocityY>0){state_.grounded=false;state_.velocityY-=config_.gravity*dt;state_.y+=state_.velocityY*dt;if(state_.y<=0){double landing=std::abs(state_.velocityY);state_.y=0;state_.velocityY=0;state_.grounded=true;if(landing>2)state_.landingOffset=-std::min(.075,landing*.006);}}else{state_.y=0;state_.velocityY=0;state_.grounded=true;}state_.x+=state_.velocityX*dt;state_.z+=state_.velocityZ*dt;state_.eyeHeight=moveToward(state_.eyeHeight,targetEyeHeight(),config_.eyeHeightTransitionSpeed*dt);state_.landingOffset=moveToward(state_.landingOffset,0,.38*dt);updateCameraFeel(dt,s,previousSpeed);state_.previousHorizontalSpeed=horizontalSpeed();}
void CharacterMotor::applyHorizontalCollision(double x,double z,bool hx,bool hz)noexcept{if(!std::isfinite(x)||!std::isfinite(z))return;state_.x=x;state_.z=z;if(hx)state_.velocityX=0;if(hz)state_.velocityZ=0;}
void CharacterMotor::updateCameraFeel(double dt,double strafe,double previousSpeed)noexcept{double speed=horizontalSpeed(),bob=0,roll=0;switch(state_.gait){case CharacterGait::Idle:break;case CharacterGait::Walk:bob=.010;roll=.006;break;case CharacterGait::Tactical:bob=.016;roll=.008;break;case CharacterGait::Jog:bob=.026;roll=.012;break;case CharacterGait::Sprint:bob=.034;roll=.016;break;case CharacterGait::Crouch:bob=.011;roll=.006;break;case CharacterGait::Crawl:bob=.004;roll=.003;break;}if(state_.grounded&&speed>.12&&bob>0){state_.stepPhase=wrapAngle(state_.stepPhase+speed*dt*2.15);state_.cameraBobY=moveToward(state_.cameraBobY,std::sin(state_.stepPhase*2)*bob,.35*dt);state_.cameraRoll=moveToward(state_.cameraRoll,std::sin(state_.stepPhase)*roll+std::clamp(strafe,-1.0,1.0)*.008,.28*dt);}else{state_.cameraBobY=moveToward(state_.cameraBobY,0,.30*dt);state_.cameraRoll=moveToward(state_.cameraRoll,0,.24*dt);}double acceleration=(speed-previousSpeed)/std::max(dt,1e-6);double leanTarget=std::clamp(-acceleration*.0018,-.018,.018)+std::clamp(strafe,-1.0,1.0)*-.010;state_.cameraLean=moveToward(state_.cameraLean,leanTarget,.16*dt);}
double CharacterMotor::cameraYaw()const noexcept{return wrapAngle(state_.bodyYaw+state_.viewYawOffset);}double CharacterMotor::cameraHeight()const noexcept{return std::max(.20,state_.eyeHeight+state_.cameraBobY+state_.landingOffset);}double CharacterMotor::horizontalSpeed()const noexcept{return std::hypot(state_.velocityX,state_.velocityZ);}double CharacterMotor::capsuleHeight()const noexcept{switch(state_.stance){case CharacterStance::Standing:return config_.standingCapsuleHeight;case CharacterStance::Crouched:return config_.crouchedCapsuleHeight;case CharacterStance::Prone:return config_.proneCapsuleHeight;}return config_.standingCapsuleHeight;}
bool CharacterMotor::validate()const noexcept{auto f=[](double v){return std::isfinite(v);};if(!f(state_.x)||!f(state_.y)||!f(state_.z)||!f(state_.velocityX)||!f(state_.velocityY)||!f(state_.velocityZ)||!f(state_.bodyYaw)||!f(state_.viewYawOffset)||!f(state_.pitch)||!f(state_.eyeHeight)||state_.eyeHeight<=0||!f(state_.cameraBobY)||std::abs(state_.cameraBobY)>.12||!f(state_.cameraRoll)||std::abs(state_.cameraRoll)>.08||!f(state_.cameraLean)||std::abs(state_.cameraLean)>.05||!f(state_.landingOffset)||state_.landingOffset>1e-6||state_.landingOffset<-.10||state_.y<-1e-6||std::abs(state_.viewYawOffset)>config_.viewYawHardLimit+1e-6||std::abs(state_.pitch)>config_.maxPitch+1e-6)return false;if(state_.sprinting&&(state_.stance!=CharacterStance::Standing||state_.gait!=CharacterGait::Sprint))return false;return pf(capsuleHeight())&&pf(config_.capsuleRadius);}
#ifdef METSE_TESTING
void CharacterMotor::testOnlySetAirborne(double h,double vy)noexcept{if(!std::isfinite(h)||!std::isfinite(vy))return;state_.y=std::max(0.0,h);state_.velocityY=vy;state_.grounded=state_.y<=0&&state_.velocityY<=0;}
#endif
double CharacterMotor::moveToward(double c,double t,double d)noexcept{if(c<t)return std::min(c+d,t);if(c>t)return std::max(c-d,t);return t;}double CharacterMotor::wrapAngle(double r)noexcept{return std::remainder(r,6.28318530717958647692);}double CharacterMotor::targetEyeHeight()const noexcept{switch(state_.stance){case CharacterStance::Standing:return config_.standingEyeHeight;case CharacterStance::Crouched:return config_.crouchedEyeHeight;case CharacterStance::Prone:return config_.proneEyeHeight;}return config_.standingEyeHeight;}
} // namespace metse
