#include "METSEEngineCore.hpp"
#include <algorithm>
#include <bit>
#include <cmath>
#include <cstring>
#include <limits>

namespace metse { namespace {bool eq(double a,double b,double e=1e-8){return std::abs(a-b)<=e;}void put64(std::array<std::uint8_t,256>&b,std::size_t&c,std::uint64_t v){for(int i=7;i>=0;--i)b[c++]=static_cast<std::uint8_t>(v>>(i*8));}void putD(std::array<std::uint8_t,256>&b,std::size_t&c,double v){put64(b,c,std::bit_cast<std::uint64_t>(v));}}
EngineCore::EngineCore(EngineConfig c):config_(c),character_(c.character),weapon_(c.weapon){if(!std::isfinite(config_.fixedStepSeconds)||config_.fixedStepSeconds<=0)config_.fixedStepSeconds=1.0/60.0;config_.maxCatchUpSteps=std::clamp<std::uint32_t>(config_.maxCatchUpSteps,1,8);config_.maxCombatants=std::clamp<std::uint32_t>(config_.maxCombatants,1,32);config_.character=character_.config();config_.weapon=weapon_.config();resetState();integrity_.appendSystemEvent(EventKind::EngineBoot,0);}
void EngineCore::resetState()noexcept{state_={};accumulatorSeconds_=0;moveForward_=moveStrafe_=0;sprintHeld_=false;character_.reset();weapon_.reset();ballistics_.reset();damage_.reset();visibility_.reset();observatory_.reset();inputQueue_.reset();sessionCollisionContacts_=simulationInvariantRollbacks_=lastDamageResultSequence_=0;frameCollisionContacts_=0;for(std::size_t i=0;i<damage_.targetCount();++i){const auto&t=damage_.targets()[i];visibility_.syncTarget(i,t.id,t.position,t.alive);}visibility_.update(cameraPosition(),character_.cameraYaw());syncSnapshot();}
void EngineCore::reset(){executeAtomic(CommandKind::ResetSession,true,EventKind::SessionReset,[&](std::uint64_t){resetState();blackBox_={};blackBoxWrite_=blackBoxCount_=0;return true;});}
bool EngineCore::setActiveCombatants(std::uint32_t n){return executeAtomic(CommandKind::SetActiveCombatants,n<=config_.maxCombatants,EventKind::CombatantCountChanged,[&](std::uint64_t){state_.activeCombatants=n;return true;});}
Vec3 EngineCore::cameraPosition()const noexcept{return {character_.state().x,character_.state().y+character_.cameraHeight(),character_.state().z};}
void EngineCore::drainInputQueue()noexcept{InputCommand cmd{};std::size_t drained=0;while(drained<InputCommandQueue::kCapacity&&inputQueue_.pop(cmd)){++drained;switch(cmd.kind){case InputCommandKind::Move:moveForward_=cmd.a;moveStrafe_=cmd.b;break;case InputCommandKind::Look:character_.addLookInput(cmd.a,cmd.b);break;case InputCommandKind::Sprint:sprintHeld_=cmd.flag;break;case InputCommandKind::Aim:weapon_.setAimHeld(cmd.flag);break;case InputCommandKind::Fire:case InputCommandKind::Reload:case InputCommandKind::CycleStance:applyDiscrete(cmd);break;}}syncSnapshot();}
void EngineCore::applyDiscrete(const InputCommand&cmd)noexcept{switch(cmd.kind){case InputCommandKind::Fire:{const auto&w=weapon_.state();bool ready=!w.reloading&&!w.obstructed&&w.fireCooldown<=0.0&&w.ammoInMagazine>0&&ballistics_.activeCount()<BallisticsCore::kMaxProjectiles;executeAtomic(CommandKind::FireWeapon,ready,EventKind::ShotFired,[&](std::uint64_t id){ShotSolution shot{};if(!weapon_.fire(cameraPosition(),character_.cameraYaw(),character_.state().pitch,id,shot))return false;if(!ballistics_.spawn(shot))return false;++state_.shotsFired;return true;});break;}case InputCommandKind::Reload:{const auto&w=weapon_.state();bool can=!w.reloading&&w.ammoInMagazine<weapon_.config().magazineSize&&w.reserveAmmo>0;executeAtomic(CommandKind::ReloadWeapon,can,EventKind::ReloadStarted,[&](std::uint64_t){return weapon_.requestReload();});break;}case InputCommandKind::CycleStance:executeAtomic(CommandKind::CycleStance,true,EventKind::StanceChanged,[&](std::uint64_t){CharacterMotor before=character_;character_.cycleStance();double clearance=world_.clearanceHeightAt(character_.state().x,character_.state().z,character_.config().capsuleRadius);if(std::isfinite(clearance)&&character_.capsuleHeight()>clearance-0.02){character_=before;return false;}return true;});break;default:break;}}
void EngineCore::advance(double realDt){frameCollisionContacts_=0;drainInputQueue();if(!std::isfinite(realDt)||realDt<=0){state_.interpolationAlpha=std::clamp(accumulatorSeconds_/config_.fixedStepSeconds,0.0,1.0);recordBlackBox(0,0,false);return;}double maxDelta=config_.fixedStepSeconds*config_.maxCatchUpSteps;bool inputClamped=realDt>maxDelta;accumulatorSeconds_+=std::min(realDt,maxDelta);std::uint32_t steps=0;while(accumulatorSeconds_>=config_.fixedStepSeconds&&steps<config_.maxCatchUpSteps){fixedStep();accumulatorSeconds_-=config_.fixedStepSeconds;++steps;}bool backlog=false;if(steps==config_.maxCatchUpSteps&&accumulatorSeconds_>=config_.fixedStepSeconds){accumulatorSeconds_=std::fmod(accumulatorSeconds_,config_.fixedStepSeconds);backlog=true;}bool clamped=inputClamped||backlog;state_.interpolationAlpha=std::clamp(accumulatorSeconds_/config_.fixedStepSeconds,0.0,1.0);recordBlackBox(realDt,steps,clamped);observeFrame(realDt,steps,clamped);}
void EngineCore::updateWeaponObstruction()noexcept{Vec3 c=cameraPosition();double yaw=character_.cameraYaw(),pitch=character_.state().pitch;double cp=std::cos(pitch),sp=std::sin(pitch),sy=std::sin(yaw),cy=std::cos(yaw);Vec3 forward{sy*cp,sp,cy*cp};Vec3 to{c.x+forward.x*.62,c.y+forward.y*.62-.08,c.z+forward.z*.62};weapon_.setObstructed(world_.raycastSegment(c,to).hit);}
void EngineCore::fixedStep()noexcept{EngineSnapshot stateCp=state_;CharacterMotor charCp=character_;WeaponCore weaponCp=weapon_;BallisticsCore ballCp=ballistics_;DamageCore damageCp=damage_;VisibilityCore visCp=visibility_;auto contactsCp=sessionCollisionContacts_;auto frameCp=frameCollisionContacts_;double px=character_.state().x,pz=character_.state().z;CharacterInput in{moveForward_,moveStrafe_,sprintHeld_};character_.fixedStep(config_.fixedStepSeconds,in);auto col=world_.resolve(px,pz,character_.state().x,character_.state().z,character_.config().capsuleRadius,character_.capsuleHeight());character_.applyHorizontalCollision(col.x,col.z,col.hitX,col.hitZ);frameCollisionContacts_+=col.contacts;sessionCollisionContacts_+=col.contacts;updateWeaponObstruction();bool wasReloading=weapon_.state().reloading;weapon_.fixedStep(config_.fixedStepSeconds,character_.horizontalSpeed(),moveStrafe_);if(wasReloading&&!weapon_.state().reloading)integrity_.appendSystemEvent(EventKind::ReloadCompleted,state_.simulationTick+1);ballistics_.fixedStep(config_.fixedStepSeconds,world_,damage_);if(damage_.resultSequence()!=lastDamageResultSequence_){lastDamageResultSequence_=damage_.resultSequence();const auto&r=damage_.lastResult();integrity_.appendCorrelatedSystemEvent(EventKind::DamageApplied,r.correlationId,state_.simulationTick+1);if(r.killed)integrity_.appendCorrelatedSystemEvent(EventKind::TargetKilled,r.correlationId,state_.simulationTick+1);}for(std::size_t i=0;i<damage_.targetCount();++i){const auto&t=damage_.targets()[i];visibility_.syncTarget(i,t.id,t.position,t.alive);}visibility_.update(cameraPosition(),character_.cameraYaw());state_.simulationSeconds+=config_.fixedStepSeconds;++state_.simulationTick;syncSnapshot();if(!validateInvariants()){state_=stateCp;character_=charCp;weapon_=weaponCp;ballistics_=ballCp;damage_=damageCp;visibility_=visCp;sessionCollisionContacts_=contactsCp;frameCollisionContacts_=frameCp;++simulationInvariantRollbacks_;integrity_.appendSystemEvent(EventKind::SimulationInvariantRolledBack,state_.simulationTick);}}
void EngineCore::syncSnapshot()noexcept{const auto&c=character_.state();const auto&w=weapon_.state();state_.playerX=c.x;state_.playerY=c.y;state_.playerZ=c.z;state_.velocityX=c.velocityX;state_.velocityY=c.velocityY;state_.velocityZ=c.velocityZ;state_.playerBodyYaw=c.bodyYaw;state_.playerYaw=character_.cameraYaw();state_.playerPitch=c.pitch;state_.cameraHeight=character_.cameraHeight();state_.cameraRoll=c.cameraRoll;state_.cameraLean=c.cameraLean;state_.horizontalSpeed=character_.horizontalSpeed();state_.stance=c.stance;state_.gait=c.gait;state_.grounded=c.grounded;state_.sprinting=c.sprinting;state_.collisionContacts=sessionCollisionContacts_;state_.ammoInMagazine=w.ammoInMagazine;state_.reserveAmmo=w.reserveAmmo;state_.adsAlpha=w.adsAlpha;state_.reloadRemaining=w.reloadRemaining;state_.reloading=w.reloading;state_.weaponObstructed=w.obstructed;state_.recoilPitch=w.recoilPitch;state_.recoilYaw=w.recoilYaw;state_.weaponSwayX=w.swayX;state_.weaponSwayY=w.swayY;state_.activeProjectiles=static_cast<std::uint32_t>(ballistics_.activeCount());state_.damageHits=damage_.totalHits();state_.damageKills=damage_.totalKills();state_.visibility=visibility_.report();state_.primaryTargetHealth=damage_.targetCount()?damage_.targets()[0].health:0;}
bool EngineCore::validateInvariants()const noexcept{if(!std::isfinite(config_.fixedStepSeconds)||config_.fixedStepSeconds<=0||config_.maxCatchUpSteps<1||config_.maxCatchUpSteps>8||config_.maxCombatants<1||config_.maxCombatants>32||state_.activeCombatants>config_.maxCombatants||!std::isfinite(state_.simulationSeconds)||state_.simulationSeconds<0||!std::isfinite(state_.interpolationAlpha)||state_.interpolationAlpha<0||state_.interpolationAlpha>1||!std::isfinite(moveForward_)||!std::isfinite(moveStrafe_)||std::hypot(moveForward_,moveStrafe_)>1.000001)return false;if(!character_.validate()||!weapon_.validate()||!world_.validate()||!ballistics_.validate()||!damage_.validate()||!visibility_.validate()||!inputQueue_.validate())return false;double clearance=world_.clearanceHeightAt(character_.state().x,character_.state().z,character_.config().capsuleRadius);if(std::isfinite(clearance)&&character_.capsuleHeight()>clearance-0.005)return false;const auto&c=character_.state();const auto&w=weapon_.state();if(!eq(state_.playerX,c.x)||!eq(state_.playerY,c.y)||!eq(state_.playerZ,c.z)||!eq(state_.playerYaw,character_.cameraYaw())||!eq(state_.cameraHeight,character_.cameraHeight())||state_.stance!=c.stance||state_.gait!=c.gait||state_.grounded!=c.grounded||state_.ammoInMagazine!=w.ammoInMagazine||state_.reserveAmmo!=w.reserveAmmo||!eq(state_.adsAlpha,w.adsAlpha)||state_.activeProjectiles!=ballistics_.activeCount()||state_.damageHits!=damage_.totalHits()||state_.damageKills!=damage_.totalKills())return false;return true;}
void EngineCore::recordBlackBox(double dt,std::uint32_t steps,bool clamped)noexcept{BlackBoxFrame f{};f.simulationTick=state_.simulationTick;f.realDeltaSeconds=dt;f.playerX=state_.playerX;f.playerY=state_.playerY;f.playerZ=state_.playerZ;f.horizontalSpeed=state_.horizontalSpeed;f.adsAlpha=state_.adsAlpha;f.queueDepth=static_cast<std::uint32_t>(inputQueue_.size());f.activeProjectiles=state_.activeProjectiles;f.catchUpSteps=steps;f.shotsFired=state_.shotsFired;f.damageHits=state_.damageHits;f.stance=state_.stance;f.gait=state_.gait;f.grounded=state_.grounded;f.sprinting=state_.sprinting;f.reloading=state_.reloading;f.catchUpClamped=clamped;blackBox_[blackBoxWrite_]=f;blackBoxWrite_=(blackBoxWrite_+1)%kBlackBoxCapacity;blackBoxCount_=std::min(blackBoxCount_+1,kBlackBoxCapacity);}
void EngineCore::observeFrame(double dt,std::uint32_t steps,bool clamped)noexcept{ObservatoryFrameInput i{};i.simulationTick=state_.simulationTick;i.realDeltaSeconds=dt;i.playerX=state_.playerX;i.playerZ=state_.playerZ;i.horizontalSpeed=state_.horizontalSpeed;i.stance=state_.stance;i.gait=state_.gait;i.grounded=state_.grounded;i.sprinting=state_.sprinting;i.catchUpSteps=steps;i.catchUpClamped=clamped;i.collisionContacts=frameCollisionContacts_;i.inputQueueDepth=static_cast<std::uint32_t>(inputQueue_.size());i.activeProjectiles=state_.activeProjectiles;i.visibilityFull=state_.visibility.full;i.visibilityReduced=state_.visibility.reduced;i.visibilityMinimal=state_.visibility.minimal;i.visibilityDormant=state_.visibility.dormant;i.ammoInMagazine=state_.ammoInMagazine;i.reserveAmmo=state_.reserveAmmo;i.adsAlpha=state_.adsAlpha;i.reloading=state_.reloading;i.weaponObstructed=state_.weaponObstructed;observatory_.observe(i);}
Sha256Digest EngineCore::deterministicStateHash()const noexcept{std::array<std::uint8_t,256>b{};std::size_t c=0;put64(b,c,state_.simulationTick);putD(b,c,state_.simulationSeconds);putD(b,c,state_.playerX);putD(b,c,state_.playerY);putD(b,c,state_.playerZ);putD(b,c,state_.velocityX);putD(b,c,state_.velocityY);putD(b,c,state_.velocityZ);putD(b,c,state_.playerYaw);putD(b,c,state_.playerPitch);put64(b,c,state_.shotsFired);put64(b,c,state_.ammoInMagazine);put64(b,c,state_.reserveAmmo);putD(b,c,state_.adsAlpha);put64(b,c,state_.damageHits);put64(b,c,state_.damageKills);put64(b,c,state_.activeProjectiles);return sha256(std::span<const std::uint8_t>(b.data(),c));}
EngineDiagnostics EngineCore::diagnostics()const noexcept{EngineDiagnostics d{};d.integrity=integrity_.metrics();d.journalHead=integrity_.journalHead();d.stateHash=deterministicStateHash();d.observatory=observatory_.report();d.inputQueue=inputQueue_.metrics();d.ballistics=ballistics_.metrics();d.visibility=visibility_.report();d.retainedEvents=integrity_.eventCount();d.retainedCommands=integrity_.commandCount();d.retainedBlackBoxFrames=blackBoxCount_;d.worldObstacleCount=world_.obstacleCount();d.inputQueueDepth=inputQueue_.size();d.sessionCollisionContacts=sessionCollisionContacts_;d.simulationInvariantRollbacks=simulationInvariantRollbacks_;d.damageHits=damage_.totalHits();d.damageKills=damage_.totalKills();d.journalValid=integrity_.verifyJournal();d.worldValid=world_.validate();d.observatoryValid=observatory_.validate();d.inputQueueValid=inputQueue_.validate();d.weaponValid=weapon_.validate();d.ballisticsValid=ballistics_.validate();d.damageValid=damage_.validate();d.visibilityValid=visibility_.validate();return d;}
bool EngineCore::newestBlackBoxFrame(std::size_t off,BlackBoxFrame&out)const noexcept{if(off>=blackBoxCount_)return false;out=blackBox_[(blackBoxWrite_+kBlackBoxCapacity-1-off)%kBlackBoxCapacity];return true;}
#ifdef METSE_TESTING
bool EngineCore::testOnlyExecuteInvariantViolation(){return executeAtomic(CommandKind::AddLookIntent,true,EventKind::LookIntentChanged,[&](std::uint64_t){moveForward_=std::numeric_limits<double>::quiet_NaN();return true;});}void EngineCore::testOnlySetAirborne(double h,double vy)noexcept{character_.testOnlySetAirborne(h,vy);syncSnapshot();}
#endif
} // namespace metse
