#include "METSEObservatoryCore.hpp"
#include <algorithm>
#include <cmath>
namespace metse {
void ObservatoryCore::reset()noexcept{*this=ObservatoryCore{};}
void ObservatoryCore::observe(const ObservatoryFrameInput&i)noexcept{if(!std::isfinite(i.realDeltaSeconds)||i.realDeltaSeconds<0||!std::isfinite(i.playerX)||!std::isfinite(i.playerZ)||!std::isfinite(i.horizontalSpeed)||i.horizontalSpeed<0||!std::isfinite(i.adsAlpha))return;double ms=i.realDeltaSeconds*1000;ObservatoryFrame f{i.simulationTick,ms,i.horizontalSpeed,i.catchUpSteps,i.collisionContacts,i.inputQueueDepth,i.activeProjectiles,i.stance,i.gait,i.grounded,i.sprinting,i.catchUpClamped};frames_[frameWrite_]=f;frameWrite_=(frameWrite_+1)%kFrameCapacity;frameCount_=std::min(frameCount_+1,kFrameCapacity);++observedFrames_;if(ms>20)++framesOver20ms_;if(ms>33.333333)++framesOver33ms_;if(i.catchUpClamped)++catchUpClampedFrames_;totalCollisionContacts_+=i.collisionContacts;peakHorizontalSpeed_=std::max(peakHorizontalSpeed_,i.horizontalSpeed);if(hasPreviousPosition_){double d=std::hypot(i.playerX-previousX_,i.playerZ-previousZ_);if(std::isfinite(d)&&d<5)distanceTravelled_+=d;if(i.stance!=previousStance_)++stanceTransitions_;if(i.gait!=previousGait_)++gaitTransitions_;}previousX_=i.playerX;previousZ_=i.playerZ;previousStance_=i.stance;previousGait_=i.gait;hasPreviousPosition_=true;if(i.sprinting)sprintSeconds_+=i.realDeltaSeconds;if(!i.grounded)airborneSeconds_+=i.realDeltaSeconds;switch(i.stance){case CharacterStance::Standing:standingSeconds_+=i.realDeltaSeconds;break;case CharacterStance::Crouched:crouchedSeconds_+=i.realDeltaSeconds;break;case CharacterStance::Prone:proneSeconds_+=i.realDeltaSeconds;break;}latestQueueDepth_=i.inputQueueDepth;peakQueueDepth_=std::max(peakQueueDepth_,i.inputQueueDepth);latestProjectiles_=i.activeProjectiles;peakProjectiles_=std::max(peakProjectiles_,i.activeProjectiles);latestVisibilityFull_=i.visibilityFull;latestVisibilityReduced_=i.visibilityReduced;latestVisibilityMinimal_=i.visibilityMinimal;latestVisibilityDormant_=i.visibilityDormant;latestAmmo_=i.ammoInMagazine;latestReserveAmmo_=i.reserveAmmo;latestAdsAlpha_=i.adsAlpha;latestReloading_=i.reloading;latestWeaponObstructed_=i.weaponObstructed;}
ObservatoryReport ObservatoryCore::report()const noexcept{ObservatoryReport o{};o.observedFrames=observedFrames_;o.retainedFrames=frameCount_;o.framesOver20ms=framesOver20ms_;o.framesOver33ms=framesOver33ms_;o.catchUpClampedFrames=catchUpClampedFrames_;o.totalCollisionContacts=totalCollisionContacts_;o.distanceTravelled=distanceTravelled_;o.peakHorizontalSpeed=peakHorizontalSpeed_;o.sprintSeconds=sprintSeconds_;o.airborneSeconds=airborneSeconds_;o.standingSeconds=standingSeconds_;o.crouchedSeconds=crouchedSeconds_;o.proneSeconds=proneSeconds_;o.stanceTransitions=stanceTransitions_;o.gaitTransitions=gaitTransitions_;o.latestQueueDepth=latestQueueDepth_;o.peakQueueDepth=peakQueueDepth_;o.latestProjectiles=latestProjectiles_;o.peakProjectiles=peakProjectiles_;o.latestVisibilityFull=latestVisibilityFull_;o.latestVisibilityReduced=latestVisibilityReduced_;o.latestVisibilityMinimal=latestVisibilityMinimal_;o.latestVisibilityDormant=latestVisibilityDormant_;o.latestAmmo=latestAmmo_;o.latestReserveAmmo=latestReserveAmmo_;o.latestAdsAlpha=latestAdsAlpha_;o.latestReloading=latestReloading_;o.latestWeaponObstructed=latestWeaponObstructed_;if(!frameCount_)return o;std::array<double,kFrameCapacity>v{};double sum=0,mx=0;std::size_t oldest=(frameWrite_+kFrameCapacity-frameCount_)%kFrameCapacity;for(std::size_t n=0;n<frameCount_;++n){double x=frames_[(oldest+n)%kFrameCapacity].frameMilliseconds;v[n]=x;sum+=x;mx=std::max(mx,x);}std::sort(v.begin(),v.begin()+static_cast<std::ptrdiff_t>(frameCount_));auto pct=[&](double p){std::size_t idx=std::min(frameCount_-1,static_cast<std::size_t>(std::ceil(frameCount_*p))-1);return v[idx];};o.averageFrameMilliseconds=sum/frameCount_;o.p95FrameMilliseconds=pct(.95);o.p99FrameMilliseconds=pct(.99);double p999=pct(.999);o.maxFrameMilliseconds=mx;if(o.averageFrameMilliseconds>1e-6)o.estimatedFPS=1000/o.averageFrameMilliseconds;if(o.p99FrameMilliseconds>1e-6)o.onePercentLowFPS=1000/o.p99FrameMilliseconds;if(p999>1e-6)o.pointOnePercentLowFPS=1000/p999;return o;}
bool ObservatoryCore::newestFrame(std::size_t off,ObservatoryFrame&out)const noexcept{if(off>=frameCount_)return false;out=frames_[(frameWrite_+kFrameCapacity-1-off)%kFrameCapacity];return true;}
bool ObservatoryCore::validate()const noexcept{if(frameCount_>kFrameCapacity||frameWrite_>=kFrameCapacity||!std::isfinite(distanceTravelled_)||distanceTravelled_<0||!std::isfinite(peakHorizontalSpeed_)||peakHorizontalSpeed_<0||!std::isfinite(latestAdsAlpha_)||latestAdsAlpha_<0||latestAdsAlpha_>1.0001||peakQueueDepth_>64||peakProjectiles_>128)return false;for(std::size_t i=0;i<frameCount_;++i){ObservatoryFrame f{};if(!newestFrame(i,f)||!std::isfinite(f.frameMilliseconds)||f.frameMilliseconds<0||!std::isfinite(f.horizontalSpeed)||f.horizontalSpeed<0)return false;}return true;}
} // namespace metse
