#include "METSEObservatoryCore.hpp"
#include <algorithm>
#include <cmath>
namespace metse {
void ObservatoryCore::reset() noexcept { *this = ObservatoryCore{}; }
void ObservatoryCore::observe(const ObservatoryFrameInput& i) noexcept {
    if (!std::isfinite(i.realDeltaSeconds)||i.realDeltaSeconds<0.0||!std::isfinite(i.simulationSliceMilliseconds)||i.simulationSliceMilliseconds<0.0||!std::isfinite(i.playerX)||!std::isfinite(i.playerZ)||!std::isfinite(i.horizontalSpeed)||i.horizontalSpeed<0.0||!std::isfinite(i.adsAlpha)) return;
    const double ms=i.realDeltaSeconds*1000.0; ObservatoryFrame f{}; f.simulationTick=i.simulationTick; f.frameMilliseconds=ms; f.simulationSliceMilliseconds=i.simulationSliceMilliseconds; f.horizontalSpeed=i.horizontalSpeed; f.catchUpSteps=i.catchUpSteps; f.collisionContacts=i.collisionContacts; f.inputQueueDepth=i.inputQueueDepth; f.activeProjectiles=i.activeProjectiles; f.aiActiveAgents=i.aiActiveAgents; f.aiLOSAgents=i.aiLOSAgents; f.aiDecisions=i.aiDecisions; f.projectileContacts=i.projectileContacts; f.projectileTerminalContacts=i.projectileTerminalContacts; f.projectileTargetContacts=i.projectileTargetContacts; f.stance=i.stance; f.gait=i.gait; f.grounded=i.grounded; f.sprinting=i.sprinting; f.catchUpClamped=i.catchUpClamped;
    frames_[frameWrite_]=f; frameWrite_=(frameWrite_+1)%kFrameCapacity; frameCount_=std::min(frameCount_+1,kFrameCapacity); ++observedFrames_; if(ms>20.0)++framesOver20ms_; if(ms>33.333333)++framesOver33ms_; if(i.simulationSliceMilliseconds>20.0)++simulationSlicesOver20ms_; if(i.catchUpClamped)++catchUpClampedFrames_; totalCollisionContacts_+=i.collisionContacts; totalProjectileContacts_+=i.projectileContacts; totalProjectileTerminalContacts_+=i.projectileTerminalContacts; totalProjectileTargetContacts_+=i.projectileTargetContacts; simulationSliceTotalMilliseconds_+=i.simulationSliceMilliseconds; maxSimulationSliceMilliseconds_=std::max(maxSimulationSliceMilliseconds_,i.simulationSliceMilliseconds); peakHorizontalSpeed_=std::max(peakHorizontalSpeed_,i.horizontalSpeed);
    if(hasPreviousPosition_){const double d=std::hypot(i.playerX-previousX_,i.playerZ-previousZ_);if(std::isfinite(d)&&d<5.0)distanceTravelled_+=d;if(i.stance!=previousStance_)++stanceTransitions_;if(i.gait!=previousGait_)++gaitTransitions_;} previousX_=i.playerX;previousZ_=i.playerZ;previousStance_=i.stance;previousGait_=i.gait;hasPreviousPosition_=true;if(i.sprinting)sprintSeconds_+=i.realDeltaSeconds;if(!i.grounded)airborneSeconds_+=i.realDeltaSeconds;switch(i.stance){case CharacterStance::Standing:standingSeconds_+=i.realDeltaSeconds;break;case CharacterStance::Crouched:crouchedSeconds_+=i.realDeltaSeconds;break;case CharacterStance::Prone:proneSeconds_+=i.realDeltaSeconds;break;}
    latestQueueDepth_=i.inputQueueDepth;peakQueueDepth_=std::max(peakQueueDepth_,i.inputQueueDepth);latestProjectiles_=i.activeProjectiles;peakProjectiles_=std::max(peakProjectiles_,i.activeProjectiles);latestVisibilityFull_=i.visibilityFull;latestVisibilityReduced_=i.visibilityReduced;latestVisibilityMinimal_=i.visibilityMinimal;latestVisibilityDormant_=i.visibilityDormant;latestAIActiveAgents_=i.aiActiveAgents;latestAILOSAgents_=i.aiLOSAgents;latestAIDecisions_=i.aiDecisions;latestAmmo_=i.ammoInMagazine;latestReserveAmmo_=i.reserveAmmo;latestAdsAlpha_=i.adsAlpha;latestReloading_=i.reloading;latestWeaponObstructed_=i.weaponObstructed;
}
ObservatoryReport ObservatoryCore::report() const noexcept { ObservatoryReport o{}; o.observedFrames=observedFrames_;o.retainedFrames=frameCount_;o.framesOver20ms=framesOver20ms_;o.framesOver33ms=framesOver33ms_;o.simulationSlicesOver20ms=simulationSlicesOver20ms_;o.catchUpClampedFrames=catchUpClampedFrames_;o.totalCollisionContacts=totalCollisionContacts_;o.totalProjectileContacts=totalProjectileContacts_;o.totalProjectileTerminalContacts=totalProjectileTerminalContacts_;o.totalProjectileTargetContacts=totalProjectileTargetContacts_;o.distanceTravelled=distanceTravelled_;o.peakHorizontalSpeed=peakHorizontalSpeed_;o.sprintSeconds=sprintSeconds_;o.airborneSeconds=airborneSeconds_;o.standingSeconds=standingSeconds_;o.crouchedSeconds=crouchedSeconds_;o.proneSeconds=proneSeconds_;o.stanceTransitions=stanceTransitions_;o.gaitTransitions=gaitTransitions_;o.latestQueueDepth=latestQueueDepth_;o.peakQueueDepth=peakQueueDepth_;o.latestProjectiles=latestProjectiles_;o.peakProjectiles=peakProjectiles_;o.latestVisibilityFull=latestVisibilityFull_;o.latestVisibilityReduced=latestVisibilityReduced_;o.latestVisibilityMinimal=latestVisibilityMinimal_;o.latestVisibilityDormant=latestVisibilityDormant_;o.latestAIActiveAgents=latestAIActiveAgents_;o.latestAILOSAgents=latestAILOSAgents_;o.latestAIDecisions=latestAIDecisions_;o.latestAmmo=latestAmmo_;o.latestReserveAmmo=latestReserveAmmo_;o.latestAdsAlpha=latestAdsAlpha_;o.latestReloading=latestReloading_;o.latestWeaponObstructed=latestWeaponObstructed_;if(!frameCount_)return o;std::array<double,kFrameCapacity>v{};double sum=0,mx=0;const std::size_t oldest=(frameWrite_+kFrameCapacity-frameCount_)%kFrameCapacity;for(std::size_t n=0;n<frameCount_;++n){const double x=frames_[(oldest+n)%kFrameCapacity].frameMilliseconds;v[n]=x;sum+=x;mx=std::max(mx,x);}std::sort(v.begin(),v.begin()+static_cast<std::ptrdiff_t>(frameCount_));const auto pct=[&](double p){const std::size_t idx=std::min(frameCount_-1,static_cast<std::size_t>(std::ceil(frameCount_*p))-1);return v[idx];};o.averageFrameMilliseconds=sum/frameCount_;o.p95FrameMilliseconds=pct(.95);o.p99FrameMilliseconds=pct(.99);o.maxFrameMilliseconds=mx;o.averageSimulationSliceMilliseconds=simulationSliceTotalMilliseconds_/static_cast<double>(observedFrames_);o.maxSimulationSliceMilliseconds=maxSimulationSliceMilliseconds_;const double p999=pct(.999);if(o.averageFrameMilliseconds>1e-6)o.estimatedFPS=1000/o.averageFrameMilliseconds;if(o.p99FrameMilliseconds>1e-6)o.onePercentLowFPS=1000/o.p99FrameMilliseconds;if(p999>1e-6)o.pointOnePercentLowFPS=1000/p999;return o; }
bool ObservatoryCore::newestFrame(std::size_t off,ObservatoryFrame&out) const noexcept { if(off>=frameCount_)return false;out=frames_[(frameWrite_+kFrameCapacity-1-off)%kFrameCapacity];return true; }
bool ObservatoryCore::validate() const noexcept { if(frameCount_>kFrameCapacity||frameWrite_>=kFrameCapacity||!std::isfinite(distanceTravelled_)||distanceTravelled_<0||!std::isfinite(peakHorizontalSpeed_)||peakHorizontalSpeed_<0||!std::isfinite(simulationSliceTotalMilliseconds_)||simulationSliceTotalMilliseconds_<0||!std::isfinite(maxSimulationSliceMilliseconds_)||maxSimulationSliceMilliseconds_<0||!std::isfinite(latestAdsAlpha_)||latestAdsAlpha_<0||latestAdsAlpha_>1.0001||peakQueueDepth_>64||peakProjectiles_>128||latestAIActiveAgents_>32||latestAILOSAgents_>32)return false;for(std::size_t i=0;i<frameCount_;++i){ObservatoryFrame f{};if(!newestFrame(i,f)||!std::isfinite(f.frameMilliseconds)||f.frameMilliseconds<0||!std::isfinite(f.simulationSliceMilliseconds)||f.simulationSliceMilliseconds<0||!std::isfinite(f.horizontalSpeed)||f.horizontalSpeed<0||f.activeProjectiles>128||f.aiActiveAgents>32||f.aiLOSAgents>32||f.aiLOSAgents>f.aiActiveAgents)return false;}return true; }
} // namespace metse
