#include "Update/METSEUpdateCenterSubsystem.h"
#include "Algo/AllOf.h"
#include "GenericPlatform/GenericPlatformMisc.h"
#include "HAL/FileManager.h"
#include "HttpModule.h"
#include "Interfaces/IHttpRequest.h"
#include "Interfaces/IHttpResponse.h"
#include "Json.h"
#include "Misc/CoreDelegates.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
namespace METSEUpdate { static constexpr int32 CoreBuild=1; static constexpr int32 ContentSchema=1; static constexpr int64 MaxPackageBytes=256ll*1024ll*1024ll; }
void UMETSEUpdateCenterSubsystem::Initialize(FSubsystemCollectionBase& Collection){Super::Initialize(Collection);LoadLocalState();}
void UMETSEUpdateCenterSubsystem::SetState(EMETSEUpdateState NewState,const FString& Message){State=NewState;OnStateChanged.Broadcast(State,Message);}
void UMETSEUpdateCenterSubsystem::CheckForUpdates(const FString& ManifestUrl){if(State==EMETSEUpdateState::Downloading||State==EMETSEUpdateState::Mounting){SetState(EMETSEUpdateState::Failed,TEXT("Update operation already in progress."));return;}if(!ManifestUrl.StartsWith(TEXT("https://"),ESearchCase::IgnoreCase)){SetState(EMETSEUpdateState::Failed,TEXT("Only HTTPS manifests are accepted."));return;}SetState(EMETSEUpdateState::Checking,TEXT("Checking manifest..."));auto Request=FHttpModule::Get().CreateRequest();Request->SetVerb(TEXT("GET"));Request->SetURL(ManifestUrl);Request->SetTimeout(30.f);Request->OnProcessRequestComplete().BindWeakLambda(this,[this](FHttpRequestPtr,FHttpResponsePtr Response,bool bSucceeded){if(!bSucceeded||!Response.IsValid()||Response->GetResponseCode()!=200||!Response->GetURL().StartsWith(TEXT("https://"),ESearchCase::IgnoreCase)){SetState(EMETSEUpdateState::Failed,TEXT("Manifest download failed."));return;}FMETSEUpdateManifest Parsed;FString Error;if(!ParseManifest(Response->GetContentAsString(),Parsed,Error)||!ValidateManifest(Parsed,Error)){SetState(EMETSEUpdateState::Failed,Error);return;}PendingManifest=MoveTemp(Parsed);SetState(EMETSEUpdateState::Idle,FString::Printf(TEXT("Update %s is ready to download."),*PendingManifest.UpdateVersion));});if(!Request->ProcessRequest())SetState(EMETSEUpdateState::Failed,TEXT("Failed to start manifest request."));}
void UMETSEUpdateCenterSubsystem::InstallLastCheckedUpdate(){FString Error;if(!ValidateManifest(PendingManifest,Error)){SetState(EMETSEUpdateState::Failed,Error);return;}DownloadPackage();}
void UMETSEUpdateCenterSubsystem::DownloadPackage(){SetState(EMETSEUpdateState::Downloading,TEXT("Downloading staged content..."));OnProgress.Broadcast(0.f);auto Request=FHttpModule::Get().CreateRequest();Request->SetVerb(TEXT("GET"));Request->SetURL(PendingManifest.PackageUrl);Request->SetTimeout(120.f);Request->OnRequestProgress64().BindWeakLambda(this,[this](FHttpRequestPtr,uint64,uint64 BytesReceived){if(PendingManifest.SizeBytes>0)OnProgress.Broadcast(FMath::Clamp(static_cast<float>(BytesReceived)/static_cast<float>(PendingManifest.SizeBytes),0.f,1.f));});Request->OnProcessRequestComplete().BindWeakLambda(this,[this](FHttpRequestPtr,FHttpResponsePtr Response,bool bSucceeded){if(!bSucceeded||!Response.IsValid()||Response->GetResponseCode()!=200||!Response->GetURL().StartsWith(TEXT("https://"),ESearchCase::IgnoreCase)){SetState(EMETSEUpdateState::Failed,TEXT("Package download failed."));return;}const TArray<uint8>& Bytes=Response->GetContent();if(Bytes.Num()<=0||Bytes.Num()>METSEUpdate::MaxPackageBytes){SetState(EMETSEUpdateState::Failed,TEXT("Package size is invalid or exceeds the development safety cap."));return;}if(PendingManifest.SizeBytes>0&&PendingManifest.SizeBytes!=Bytes.Num()){SetState(EMETSEUpdateState::Failed,TEXT("Downloaded size does not match manifest."));return;}SetState(EMETSEUpdateState::Verifying,TEXT("Verifying SHA-256..."));FString Error;if(!VerifySha256(Bytes,PendingManifest.PackageSha256,Error)){SetState(EMETSEUpdateState::Failed,Error);return;}const FString UpdatesDir=FPaths::Combine(FPaths::ProjectPersistentDownloadDir(),TEXT("METSEUpdates"));IFileManager::Get().MakeDirectory(*UpdatesDir,true);const FString FinalPath=FPaths::Combine(UpdatesDir,FString::Printf(TEXT("content_%s.pak"),*PendingManifest.UpdateVersion));if(!AtomicWrite(FinalPath,Bytes,Error)){SetState(EMETSEUpdateState::Failed,Error);return;}SetState(EMETSEUpdateState::Staged,TEXT("Package verified and staged."));if(!MountPakFailClosed(FinalPath,Error)){IFileManager::Get().Delete(*FinalPath,false,true,true);SetState(EMETSEUpdateState::Failed,Error);return;}PreviousContentVersion=ActiveContentVersion;PreviousPakPath=ActivePakPath;if(!ActivePakPath.IsEmpty()&&FCoreDelegates::OnUnmountPak.IsBound())FCoreDelegates::OnUnmountPak.Execute(ActivePakPath);ActiveContentVersion=PendingManifest.UpdateVersion;ActivePakPath=FinalPath;SaveLocalState();SetState(EMETSEUpdateState::Active,FString::Printf(TEXT("Content update %s is active."),*ActiveContentVersion));OnProgress.Broadcast(1.f);});if(!Request->ProcessRequest())SetState(EMETSEUpdateState::Failed,TEXT("Failed to start package request."));}
bool UMETSEUpdateCenterSubsystem::ParseManifest(const FString& JsonText,FMETSEUpdateManifest& Out,FString& Error)const{TSharedPtr<FJsonObject> Root;auto Reader=TJsonReaderFactory<>::Create(JsonText);if(!FJsonSerializer::Deserialize(Reader,Root)||!Root.IsValid()){Error=TEXT("Manifest JSON is invalid.");return false;}auto Req=[&](const TCHAR* N,FString& V){if(!Root->TryGetStringField(N,V)||V.IsEmpty()){Error=FString::Printf(TEXT("Manifest field '%s' is missing."),N);return false;}return true;};if(!Req(TEXT("updateVersion"),Out.UpdateVersion)||!Req(TEXT("channel"),Out.Channel)||!Req(TEXT("packageUrl"),Out.PackageUrl)||!Req(TEXT("packageSha256"),Out.PackageSha256)||!Req(TEXT("packageType"),Out.PackageType)||!Req(TEXT("minimumCoreVersion"),Out.MinimumCoreVersion))return false;double N=0;if(Root->TryGetNumberField(TEXT("requiresAppBuild"),N))Out.RequiresAppBuild=(int32)N;if(Root->TryGetNumberField(TEXT("contentSchema"),N))Out.ContentSchema=(int32)N;if(Root->TryGetNumberField(TEXT("sizeBytes"),N))Out.SizeBytes=(int64)N;Root->TryGetBoolField(TEXT("restartRequired"),Out.bRestartRequired);Root->TryGetStringField(TEXT("mountPoint"),Out.MountPoint);return true;}
bool UMETSEUpdateCenterSubsystem::ValidateManifest(const FMETSEUpdateManifest& M,FString& E)const{if(M.UpdateVersion.IsEmpty()){E=TEXT("No valid update has been checked yet.");return false;}if(!M.PackageUrl.StartsWith(TEXT("https://"),ESearchCase::IgnoreCase)){E=TEXT("Package URL must use HTTPS.");return false;}if(M.PackageType!=TEXT("content_patch")){E=TEXT("Only content_patch packages are allowed.");return false;}if(!(M.Channel==TEXT("stable")||M.Channel==TEXT("development")||M.Channel==TEXT("experimental"))){E=TEXT("Update channel is invalid.");return false;}if(M.MinimumCoreVersion!=TEXT("0.1.0")){E=TEXT("Patch minimumCoreVersion is incompatible.");return false;}if(M.UpdateVersion.Len()>64||!Algo::AllOf(M.UpdateVersion,[](TCHAR C){return FChar::IsAlnum(C)||C==TCHAR('.')||C==TCHAR('-')||C==TCHAR('_');})){E=TEXT("Update version contains unsafe characters.");return false;}if(M.RequiresAppBuild!=METSEUpdate::CoreBuild){E=TEXT("Patch requires a different app/core build.");return false;}if(M.ContentSchema!=METSEUpdate::ContentSchema){E=TEXT("Patch content schema is incompatible.");return false;}if(M.PackageSha256.Len()!=64||!Algo::AllOf(M.PackageSha256,[](TCHAR C){return FChar::IsHexDigit(C);})){E=TEXT("Manifest SHA-256 is invalid.");return false;}if(M.SizeBytes<=0||M.SizeBytes>METSEUpdate::MaxPackageBytes){E=TEXT("Manifest package size violates safety limits.");return false;}return true;}
bool UMETSEUpdateCenterSubsystem::VerifySha256(const TArray<uint8>& Data,const FString& Expected,FString& E)const{FSHA256Signature S;if(!FPlatformMisc::GetSHA256Signature(Data.GetData(),static_cast<uint32>(Data.Num()),S)){E=TEXT("Platform SHA-256 calculation failed.");return false;}if(!S.ToString().Equals(Expected,ESearchCase::IgnoreCase)){E=TEXT("SHA-256 mismatch. Staged update rejected.");return false;}return true;}
bool UMETSEUpdateCenterSubsystem::AtomicWrite(const FString& FinalPath,const TArray<uint8>& Data,FString& E)const{const FString TempPath=FinalPath+TEXT(".staging");IFileManager::Get().Delete(*TempPath,false,true,true);if(!FFileHelper::SaveArrayToFile(Data,*TempPath)){E=TEXT("Could not write staging package.");return false;}if(IFileManager::Get().FileSize(*TempPath)!=Data.Num()){IFileManager::Get().Delete(*TempPath,false,true,true);E=TEXT("Staging file size verification failed.");return false;}IFileManager::Get().Delete(*FinalPath,false,true,true);if(!IFileManager::Get().Move(*FinalPath,*TempPath,true,true,false,true)){IFileManager::Get().Delete(*TempPath,false,true,true);E=TEXT("Atomic commit of staged package failed.");return false;}return true;}
bool UMETSEUpdateCenterSubsystem::MountPakFailClosed(const FString& PakPath,FString& E)const{const_cast<UMETSEUpdateCenterSubsystem*>(this)->SetState(EMETSEUpdateState::Mounting,TEXT("Mounting verified package..."));if(!FCoreDelegates::MountPak.IsBound()){E=TEXT("Unreal PAK mount handler is unavailable. Update not activated.");return false;}return FCoreDelegates::MountPak.Execute(PakPath,100)!=nullptr||(E=TEXT("PAK mount failed. Active content remains unchanged."),false);}
bool UMETSEUpdateCenterSubsystem::RollbackToPrevious(){if(PreviousPakPath.IsEmpty()||!IFileManager::Get().FileExists(*PreviousPakPath)){SetState(EMETSEUpdateState::Failed,TEXT("No previous content package is available."));return false;}if(!FCoreDelegates::MountPak.IsBound()||FCoreDelegates::MountPak.Execute(PreviousPakPath,101)==nullptr){SetState(EMETSEUpdateState::Failed,TEXT("Rollback mount failed."));return false;}if(!ActivePakPath.IsEmpty()&&FCoreDelegates::OnUnmountPak.IsBound())FCoreDelegates::OnUnmountPak.Execute(ActivePakPath);Swap(ActivePakPath,PreviousPakPath);Swap(ActiveContentVersion,PreviousContentVersion);SaveLocalState();SetState(EMETSEUpdateState::Active,FString::Printf(TEXT("Rolled back to %s."),*ActiveContentVersion));return true;}
void UMETSEUpdateCenterSubsystem::LoadLocalState(){const FString P=FPaths::Combine(FPaths::ProjectSavedDir(),TEXT("METSEUpdateState.ini"));GConfig->GetString(TEXT("Update"),TEXT("ActiveContentVersion"),ActiveContentVersion,P);GConfig->GetString(TEXT("Update"),TEXT("PreviousContentVersion"),PreviousContentVersion,P);GConfig->GetString(TEXT("Update"),TEXT("ActivePakPath"),ActivePakPath,P);GConfig->GetString(TEXT("Update"),TEXT("PreviousPakPath"),PreviousPakPath,P);if(ActiveContentVersion.IsEmpty())ActiveContentVersion=TEXT("base");}
void UMETSEUpdateCenterSubsystem::SaveLocalState()const{const FString P=FPaths::Combine(FPaths::ProjectSavedDir(),TEXT("METSEUpdateState.ini"));GConfig->SetString(TEXT("Update"),TEXT("ActiveContentVersion"),*ActiveContentVersion,P);GConfig->SetString(TEXT("Update"),TEXT("PreviousContentVersion"),*PreviousContentVersion,P);GConfig->SetString(TEXT("Update"),TEXT("ActivePakPath"),*ActivePakPath,P);GConfig->SetString(TEXT("Update"),TEXT("PreviousPakPath"),*PreviousPakPath,P);GConfig->Flush(false,P);}
